app:
  name: book-rental-backend
  address: localhost
  port: 8080

database:
  host: localhost
  port: 5672
  user: postgres
  password: postgres
  name: rental

cache:
  type: redis
  host: redis
  port: 6379
  username:
  password:
  ssl: false

object_storage:
  type: minio
  access_key: minioadmin
  secret_key: minioadmin
  host: minio
  region: ap-southeast-1

message_broker:
  type: kafka
  username:
  password:
  brokers: 
    - "localhost:9092"
    - "localhost:9093"