# Builder Stage
FROM node:22.12.0-alpine3.21 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Runtime Stage
FROM nginx:alpine AS runtime

COPY --from=builder /app/build /etc/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]