FROM golang:1.23.4-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o backend ./cmd/api/main.go

# Runtime Stage
FROM alpine:3.21 AS runtime

WORKDIR /app

COPY --from=builder /app/backend /app/backend
COPY --from=builder /app/app.yaml /app/app.yaml

# Assume migrations are in backend/migrations
# COPY --from=builder /app/backend/migrations /app/migrations 

EXPOSE 8080

CMD ["/app/backend"]