version: '3.9'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../infrastructure/Dockerfile.backend
    # ports:
    #   - "8080:8080"
    # environment:
    #   APP_PORT: 8080
    # depends_on:
    #   - postgres
    #   - kafka

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infrastructure/Dockerfile.frontend
    # ports:
    #   - "3000:80" # Host port 3000 will forward to container port 80 (Nginx)
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend