version: '3.9'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../infrastructure/Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - minio

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infrastructure/Dockerfile.frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  postgres:
    image: ${PG_IMAGE}
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${PG_USERNAME} -d ${PG_DATABASE}'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s

  redis:
    image: ${REDIS_IMAGE}
    ports:
      - 6379:6379

  maildev:
    image: ${MAIL_IMAGE}
    environment:
      - MAILDEV_WEB_USER=${MAIL_USERNAME}
      - MAILDEV_WEB_PASS=${MAIL_PASSWORD}
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_OUTGOING_USER=${MAIL_USERNAME}
      - MAILDEV_OUTGOING_PASS=${MAIL_PASSWORD}
      - MAILDEV_INCOMING_USER=${MAIL_USERNAME}
      - MAILDEV_INCOMING_PASS=${MAIL_PASSWORD}
    ports:
      - "1025:1025" # SMTP port
      - "1080:1080" # Web UI port
      
  minio:
    image: ${MINIO_IMAGE}
    ports:
      - "9000:9000"
      - "9001:9001" # Minio Console Port
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} 
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  kafka:
    image: ${KAFKA_IMAGE}
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

volumes:
  database_data:
  minio_data:

networks:
  default:
    name: app-network