version: '3.9'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../infrastructure/Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - minio

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infrastructure/Dockerfile.frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: book_rental
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.2.7-alpine
    ports:
      - 6379:6379

  maildev:
    image: maildev/maildev:2.2.1
    environment:
      - MAILDEV_WEB_USER=developer@example.com
      - MAILDEV_WEB_PASS=test1234
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_OUTGOING_USER=developer@example.com
      - MAILDEV_OUTGOING_PASS=test1234
      - MAILDEV_INCOMING_USER=developer@example.com
      - MAILDEV_INCOMING_PASS=test1234
    ports:
      - "1025:1025" # SMTP port
      - "1080:1080" # Web UI port
      
  minio:
    image: minio/minio:RELEASE.2025-01-18T00-31-37Z
    ports:
      - "9000:9000"
      - "9001:9001" # Minio Console Port
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ROOT_USER: developer
      MINIO_ROOT_PASSWORD: test1234 
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

volumes:
  database_data:
  minio_data:

networks:
  default:
    name: app-network